### ISSUE TITLE
use with large dataset?

### ISSUE THREAD

**Issue by randomgambit** [kgjerde/corporaexplorer#11]
Hello! 

I think this package looks amazing and promising! I wonder if it is possible/doable to run the shiny app with a large dataset (say about 20GB of text data). Would the package still work in that case? Or this is just for exploring small datasets?

**Comment by kgjerde** [comment]
@randomgambit Thanks for the comment! The answer is basically that the package is not designed for such use cases. The main constraint is that the data is kept in memory. Also, complex searches would be rather slow. The largest data I have tried out (with matrix, on my 16 GB RAM laptop) is about 2 GB text data (227,000 documents). If one sets the `use_matrix`parameter in `prepare_data` to `FALSE`, one can handle larger sizes than with a matrix, but simple searches will be much slower. At any rate, the recommendation would be to subset large datasets before exploring them with this package.
