### ISSUE TITLE
How Can I put this application in Shiny-Server

### ISSUE THREAD

**Issue by rickyking** [kgjerde/corporaexplorer#19]
Hi, 

It is a very interesting explorer. Is there a way to put this in Shiny-Server?

**Comment by kgjerde** [comment]
Thanks for your interest!

At the moment I can propose this hack:

1\) Install the corporaexplorer package on your Shiny Server R installation (to make sure Shiny Server can access all necessary dependencies).

2\) From the corporaexplorer source code, copy the folder "inst/explorer" to Shiny Server, and give the folder you the name you want.

3\) In that folder, edit the file "config/config.R":

Replace line 3:
~~`loaded_data <- eval(as.name(getShinyOption("corporaexplorer_data")))`~~

with:

```
library(data.table)
library(rlang)
library(magrittr)

loaded_data <- readRDS(PATH_TO_SAVED_CORPORAEXPLOREROBJECT)

shiny::shinyOptions("corporaexplorer_optional_info" = FALSE)
shiny::shinyOptions("corporaexplorer_regex_engine" = "default")
shiny::shinyOptions("corporaexplorer_use_matrix" = TRUE)
shiny::shinyOptions("corporaexplorer_allow_unreasonable_patterns" = FALSE)
shiny::shinyOptions("corporaexplorer_ui_options" = list())
shiny::shinyOptions("corporaexplorer_input_arguments" = list())
```
Where `PATH_TO_SAVED_CORPORAEXPLOREROBJECT` points at a pre-saved corporaexplorerobject in rds format with the corpus you want to explore. (Tip: if you want the data to load faster, save the corporaexplorerobject uncompressed by setting `compress = FALSE` in `saveRDS`.)

---

Then (I believe!) Shiny Server should treat this app/folder like any Shiny app. Please let me know if you try it out.

**Comment by rickyking** [comment]
Just Tried! It's perfectly working!

**Comment by kgjerde** [comment]
@rickyking Spurred by your inquiry, I have now (with commits 5883bea155db34c454d0d7cbf5aa1890ef81c34d and b4c4246b373832b8571d4a763d7c4ea5e4a10414) eliminated the need for this hack. See https://kgjerde.github.io/corporaexplorer/articles/deployment.html.
