### ISSUE TITLE
Possible Permissions problem with README link

### ISSUE THREAD

**Issue by trinker** [kgjerde/corporaexplorer#2]
Under the *Example corpora* heading in the README I see:

> A more typical corpus can be downloaded for testing here – 

with the text hyperlink: https://ndownloader.figshare.com/files/14626970.  This results in:

```
{"message": "Insufficient permissions", "code": "InsufficientPermissions"}
```

**Comment by kgjerde** [comment]
Sorry about that. Fixed.
