### ISSUE TITLE
unable to deploy to shiny server

### ISSUE THREAD

**Issue by mvsell** [kgjerde/corporaexplorer#22]
i followed instructions here: https://kgjerde.github.io/corporaexplorer/articles/deployment.html
I created my project folder and added app.R and my Rds object as per below:
```
library(corporaexplorer)
corpus <- readRDS("SEDAR_1_object.Rds")
explore(corpus)

```
The app starts up fine manually on the rserver (i.e. explore(corpus) works) but when I try to publish it the default files in the corporaexplorer library are the ones that get published - this seems to conflict with the app.R I created as well. Is that right? How do i get the right app.R to source my corpus object correctly? Thank you.
![image](https://user-images.githubusercontent.com/4479065/84195443-95860680-aa6c-11ea-8c57-9fa5a189580f.png)
![image](https://user-images.githubusercontent.com/4479065/84195631-e7c72780-aa6c-11ea-8b9b-c29d5355f7d7.png)

**Comment by kgjerde** [comment]
Hi!

I am a bit confused as to what the internal corporaexplorer package files are doing there -- you only need to have the package installed, not to engage with its internals! Also, I have not published apps through that interface, but the principle should be the same as other deployment to shiny server.

Thus: if to deploy an app manually to shiny server, all one needs to do is to follow the recipe in the link you included. That is, to have a directory with those two files as a directory in the shiny server directory.

I assume the same should be true for publishing through RStudio. What if you create an RStudio project with one folder and those two files (app.R and data file) and try to publish that app file?

**Comment by mvsell** [comment]
Hi Kristian,

First, thank you for answering my questions. I have not stated it but I
really like your package and its utility!

With respect to your last sentence, this is exactly what I tried (both on
RStudio locally and on the Rserver version) but it does not work. The app.R
as is (with the three lines) is not recognized as a standard app.r (missing
ui and server calls? - I'm only an intermediate R user so I also struggle
to understand why exactly it does not work. Deployed as is the app searches
for the corpus object in the default library, and fails. What I've done is
to move the corpus object into the library (config folder) and, while it
gets the right corpus, it is very sluggish (only 10 files in the corpus).
So i'll need to spend a bit more time understanding what I might be doing
wrong. When I deploy the tool locally it works perfectly.

Do you have any sense for how big a corpus the tool will support? Or how
one might tackle a 2 million document corpus? i.e. thousands of files and
hundreds of Gbs.

Thank you again,

**Comment by kgjerde** [comment]
Hi! Sorry for the late response.

First:

> Do you have any sense for how big a corpus the tool will support? Or how
one might tackle a 2 million document corpus? i.e. thousands of files and
hundreds of Gbs.

See #11.

Second, it is a bit difficult to know what is going on without knowing more about your setup and the data that you want to explore in the app. But at any rate you should not need to do anything in the corporaexplorer files themselves. corporaexplorer should just be installed like any other R package, and you should not publish your app from within the corporaexplorer library files.

What happens if you publish an app.R file with the following lines from an otherwise empty folder?
`library(corporaexplorer)`
`run_sotu_app()`

**Comment by kgjerde** [comment]
Closed due to inactivity.

**Comment by mvsell** [comment]
Hello Kristian - if I run the above I get the following error message. I am trying to post to shinyapps.io. There are no issues when I try to publish the default shiny app (Old Faithful).

![image](https://user-images.githubusercontent.com/4479065/125392178-b0affd80-e373-11eb-9d89-f79adaba5e1a.png)

these are the exact lines I ran:
![image](https://user-images.githubusercontent.com/4479065/125392462-33d15380-e374-11eb-8c29-2ba99aaaae37.png)

and my session info:
![image](https://user-images.githubusercontent.com/4479065/125392595-6d09c380-e374-11eb-8744-71c8d5f571d9.png)

**Comment by kgjerde** [comment]
Hi.

I could not replicate that error, but I see that you have to load the janeaustenr library as well, so shinyapps knows that it should install that package.

What happens if this is your app.R?

`library(corporaexplorer)`
`library(janeaustenr)`
`run_janeausten_app()`
