### ISSUE TITLE
App works locally but breaks when deployed to shiny-server (Ubuntu 20.04; R Version 4.04)

### ISSUE THREAD

**Issue by wrathofquan** [kgjerde/corporaexplorer#25]
I have an app hosted here: http://128.199.15.25/shiny/wapo-explorer/

of newspaper data for one year. The app works perfectly locally (OSX 11.2; R Version 4.0.3) but breaks when deployed. The corporaexplorer/rds object is recognized because I can click on tiles to view individual documents but the app is suspended when trying a keyword search. In place of the usual time slider, I see the error:

"An error has occurred. Check your logs or contact the app author for clarification."

Checking the shiny-server logs shows this:

```
Listening on http://127.0.0.1:35697
Warning: Error in min: invalid 'type' (list) of argument
  103: validate_slider_value
  102: shiny::sliderInput
   96: renderUI
   95: func
   82: renderFunc
   81: output$time_filtering_ui
    1: runApp
Warning: Error in if: argument is of length zero
  1: runApp
Warning: Error in min: invalid 'type' (list) of argument
  103: validate_slider_value
  102: shiny::sliderInput
   96: renderUI
   95: func
   82: renderFunc
   81: output$time_filtering_ui
    1: runApp
```

My app.R file:

```
library(corporaexplorer) 
corpus <- readRDS("./saved_corporaexplorerobject.rds")
explore(corpus, plot_options = list(colours = c("gray", "green", "blue", "purple")))

```

This is a wonderful app and am hoping to get it working for a project but I am stuck on debugging this particular issue. Any guidance or suggestions are greatly appreciated.

**Comment by kgjerde** [comment]
Thanks for your note. I hope this fixed it. Can you please install the dev version from github and let me know if it helped?

**Comment by wrathofquan** [comment]
Thank you! Yes, the range() fix did the trick. Cheers.

**Comment by rickyking** [comment]
Possible to push this fix to the CRAN?

**Comment by kgjerde** [comment]
> Possible to push this fix to the CRAN?

Version 0.8.4 now published on CRAN.
