### ISSUE TITLE
How to publish to shinyapps.io

### ISSUE THREAD

**Issue by rickyking** [kgjerde/corporaexplorer#27]
I tried to follow this instruction: https://kgjerde.github.io/corporaexplorer/articles/deployment.html

However I am unable to publish this to shinyapp.io. It keeps uploading the application in your folder. Do you know if there is a way to publish it on shinyapp.io?

**Comment by kgjerde** [comment]
Hi. Not really enough information to say. Have you tried to upload the app on shinyapps from scratch from a 'clean' folder, i.e. without the rsconnect folder that perhaps has collected some problems?

**Comment by rickyking** [comment]
Hi,

Thanks for your reply. Ya, actually I start with empty shiny project in RStudio with following structure:

my_app  
  |  
  |-- app.R  
  |-- saved_corporaexplorerobject.rds  

However, no publish button shows up while in `app.R` open.

![image](https://user-images.githubusercontent.com/2820809/125995142-034e6b60-8a3e-48a0-9fa4-f63e6bffe254.png)

Then I run it I am able to get a publish showing up:
![image](https://user-images.githubusercontent.com/2820809/125995240-52eb9dcc-e0c4-4631-a851-2721bbb93514.png)

I click the publish I got this: 
![image](https://user-images.githubusercontent.com/2820809/125995338-fa095c66-8378-4048-a760-6822afa8f15a.png)


It actually publishes your `inst/explorer` folder but not the right project folder.

**Comment by kgjerde** [comment]
This is really more of a rstudio usage question. I use the rsconnect package myself. See the 'Deploying apps' section at https://shiny.rstudio.com/articles/shinyapps.html.

**Comment by rickyking** [comment]
great thanks... it looks should never rely on GUI lol...
