### ISSUE TITLE
Add write on top of read only

### ISSUE THREAD

**Issue by Teolone88** [kgjerde/corporaexplorer#28]
Hi,

I find this tool very powerful and indeed with a lot of potential. I can see for writers, especially, this tool can be pushed to have also write mode by adding some rich text feature beside the read only. I was wondering, if it would be ok with you if I would play a bit with what you have created so far and present you with the additional feature.

This will allow writers to examine their writings while writing by agnostically using the metadata that they prefer to use at the beginning of the document (E.g. Chapter, Context, Audience, etc...),  especially for medium, long term writings.
I'd like to write a book, personally, and I can see in this tool an ally that would keep me on track, especially when it comes to understand what I wrote and where I wrote it.

Let me know if you are ok with this.

Best,
Teo

**Comment by kgjerde** [comment]
Hi Teo,

So very sorry for this late response, but great to hear that you find corporaexplorer useful! This is open source software, so please feel free to do anything you'd like with it! Personally, I have thought that this package works best as a limited read-only explorer. Maybe I misunderstand you, but perhaps something like Scrivener fits your need?

**Comment by kgjerde** [comment]
I close this issue, but please feel free to continue the conversation.
