### ISSUE TITLE
Explorer: Option to add check-boxes to select specific articles

### ISSUE THREAD

**Issue by discoleo** [kgjerde/corporaexplorer#30]
# Explorer: Option to add check-boxes to select specific articles

## Manual Selection

The users may want to select manually specific articles, while exploring the corpus. It would be very handy to have an option to show a column with check-boxes in the shiny app. The users can manually check the check-boxes corresponding to the desired articles.

## Filter / Export

The users could then filter these articles and export the filtered corpus:
- if there is a grouping variable: option to export only the values of the grouping variable;
- very handy to filter articles from Pubmed;

## Pubmed Example

For an example using abstracts from Pubmed, see:
https://github.com/discoleo/R/tree/master/TextMining/Pubmed
- file Pubmed.Examples.R: to download a set of abstracts from Pubmed;
- file TextMining.Examples.R: provides also an example using corporaexplorer, but could benefit from the functionality described here;

**Comment by kgjerde** [comment]
Thanks also for this input. I absolutely see the usefulness, but I will have to think a bit about it.
