### ISSUE TITLE
[prepare_data] Argument text.col = "Text"

### ISSUE THREAD

**Issue by discoleo** [kgjerde/corporaexplorer#31]
# Function prepare_data

Add argument to specify name of text column:
- new argument: text.col = "Text";

## Motivation

Corpora based on scientific articles may have multiple text columns: Title, Abtract, Text (full text). It becomes impractical to rename the columns each time one wants to process a different column.

## Solution
Enable users to specify the column name of the actual text column.

## Example
I have uploaded a csv file with 1200 Pubmed articles (Title & Abstract columns) on Github:
- see file [Example_Abstracts_Title_Pubmed.csv](https://github.com/discoleo/R/blob/master/TextMining/Pubmed/Example_Abstracts_Title_Pubmed.csv);
https://github.com/discoleo/R/tree/master/TextMining/Pubmed
```
### CSV-File
x = read.csv("Example_Abstracts_Title_Pubmed.csv")

x = x[ -3]; # remove Year column
names(x)[2] = "Text"; # currently needed!
xc = prepare_data(x,
	grouping_variable="PMID",
	date_based_corpus=FALSE)

explore(xc)
```

**Comment by kgjerde** [comment]
Hi!

Thanks for this well-considered proposal. I think this is worth implementing, and as part of that probably also look at another problem in your example which you don't mention: that 'Year' and some others are reserved column names and have to be renamed or dropped before running `prepare_data()`.

This will take a bit of internal refactoring and I am rather busy with some unrelated other things right now, so I am not quite sure when, but I will look into this.

**Comment by kgjerde** [comment]
For the record: this is now implemented (see NEWS.md)
