### ISSUE TITLE
Exact test of prepare_data() broken by latest data.table

### ISSUE THREAD

**Issue by MichaelChirico** [kgjerde/corporaexplorer#32]
https://github.com/kgjerde/corporaexplorer/blob/8e9d10b7ac923a56bd1e62757fda5373a7bfc0b9/tests/testthat/test_prep_func.R#L12

Hi, we recently made a change to improve the performance of sorting in many cases for data.table: https://github.com/Rdatatable/data.table/pull/4386

Unfortunately, that breaks the above test, which relies on an exact representation of the `test_data` object through `prepare_data()`:

```r
all.equal(test_obj, corporaexplorer::test_data)
# [1] "Component “original_matrix”: Component “data_dok”: Attributes: < Component “index”: Attributes: < Component “__i”: Attributes: < Modes: list, NULL > > >"                   
# [2] "Component “original_matrix”: Component “data_dok”: Attributes: < Component “index”: Attributes: < Component “__i”: Attributes: < Lengths: 6, 0 > > >"                       
# [3] "Component “original_matrix”: Component “data_dok”: Attributes: < Component “index”: Attributes: < Component “__i”: Attributes: < names for target but not for current > > >"
# [4] "Component “original_matrix”: Component “data_dok”: Attributes: < Component “index”: Attributes: < Component “__i”: Attributes: < current is not list-like > > >" 
```

At root, `setindex()` now adds some new attributes that are captured when `setindex()` is run within `prepare_data()`, but were not present when the `test_data.rda` object was created:

https://github.com/kgjerde/corporaexplorer/blob/8e9d10b7ac923a56bd1e62757fda5373a7bfc0b9/R/prepare_data.R#L234

Ideally, we can write the test in a way that's not sensitive to such implementation details, but because the new attribute is so deeply nested in the comparison object, it's a bit messy to do so.

I think the _best best_ solution is to write an `all.equal.corporaexplorerobject()` method that can hash out which parts of the object you actually care about for comparison.

A very simple solution, but which might not be ideal, is to pass `check.attributes=FALSE` to the test. I don't know enough context to judge if that might ignore important attributes.

We plan to release to CRAN in the next two weeks or so, so some cooperation on addressing this would be appreciated.

Thanks for using data.table!

**Comment by kgjerde** [comment]
Hi! Thank you so much for all the thought you put into this – really very much appreciated! I opted for a slightly different solution for now, outsourcing some decision-making about significant attributes to waldo (f6fa616).
