### ISSUE TITLE
`prepare_data` function creates tables with column headers of different casing

### ISSUE THREAD

**Issue by trinker** [kgjerde/corporaexplorer#4]
The `prepare_data` function creates tables with column headers of different casing.  For example 
I run this minimal example:

```
library(corporaexplorer)

dates <- as.Date(paste(2011:2020, 1:10, 21:30, sep = "-"))
texts <- paste0(
  "This is a document about ", month.name[1:10], ". ",
  "This is not a document about ", rev(month.name[1:10]), "."
)
titles <- paste("Text", 1:10)
test_df <- tibble::tibble(Date = dates, Text = texts, Title = titles)

# Converting to corporaexplorer object:
corpus <- prepare_data(test_df, corpus_name = "foo")

lapply(corpus[[1]], names)
```

And see:

```
$data_dok
[1] "Date"      "Text"      "Title"     "Year"      "wc"        "id"        "Text_case"

$data_365
 [1] "Date"      "Year"      "empty"     "wc"        "Weekday_n" "Month_n"   "Week_n"    "Yearday_n" "No."       "ID"        "mnd_vert"  "mnd_hor"   "id"     
```

There's upper, lower, and snake all mixed together.  It's nice to fix these inconsistencies (unless there's a reason for them) right from the start.

**Comment by kgjerde** [comment]
I used this suggestion to do a housecleaning of variables that no longer need to be part of the corporaexplorerobject (but were necessary in earlier iterations) and have generally improved naming in be32c83. I then addressed backwards compatibility problems in 5cfeb53.
