### ISSUE TITLE
Request ability to control search term labeling

### ISSUE THREAD

**Issue by trinker** [kgjerde/corporaexplorer#7]
The app has the ability to download charts (very nice).  Ofter we use complex, even ugly looking, regexes to search but we don't want that to be the label on plots for the common reader.  We want something with more human readable terms (`\bwar\b` below).

![image](https://user-images.githubusercontent.com/1763278/55283535-743b6d80-5333-11e9-9efb-9fb622669594.png)

It'd be nice to have the ability to give the search terms more human readable names.  This is not per the JOSS review process...just like the app and would like to see this feature.

**Comment by kgjerde** [comment]
@trinker Thanks a lot for the interest and the proposal! I have never intended this plot to be suitable for export/download, but I do see the usefulness if one wants a quick and dirty presentation of some trends, so I will come back to this.

**Comment by kgjerde** [comment]
@trinker Proposal implemented! Please let me know if you experience any problems.
